const USER_API_ENDPOINT="/api/v1/user/" 
const COURSE_API_ENDPOINT="/api/v1/course/" 
const PROGRESS_API_ENDPOINT="/api/v1/progress/" 
const PURCHASE_API_ENDPOINT="/api/v1/purchase/" 

export { USER_API_ENDPOINT , COURSE_API_ENDPOINT , PROGRESS_API_ENDPOINT , PURCHASE_API_ENDPOINT };